version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ingest1:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_1_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest1
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -- python ingest_service1.py"]

  ingest2:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_2_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest2
    depends_on:
      - ingest1
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh ingest1:80 -- python ingest_service2.py"]

  ingest3:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_3_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest3
    depends_on:
      - ingest2
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh ingest2:80 -- python ingest_service3.py"]

  ingest4:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_4_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest4
    depends_on:
      - ingest3
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh ingest3:80 -- python ingest_service4.py"]

  ingest5:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_5_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest5
    depends_on:
      - ingest4
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh ingest4:80 -- python ingest_service5.py"]

  etl:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_5_DEV}
      - S3_BUCKET=${S3_BUCKET_DEV}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=etl
    depends_on:
      - ingest5
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["sh", "-c", "./wait-for-it.sh ingest5:80 -- python etl_service.py"]

volumes:
  mysql_data:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/logs